server:
  port: 5555
  servlet:
    context-path: /account

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankAppAccountDB
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  application:
    name: BankApp-AccountService
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
resilience4j:
  circuitbreaker:
    instances:
      TransactionBreaker:
       register-health-indicator: true
       event-consumer-buffer-size: 10
       failure-rate-threshold: 50
       minimum-number-of-calls: 5
       automatic-transition-from-open-to-half-open-enabled: true
       wait-duration-in-open-state: 6s
       permitted-number-of-calls-in-half-open-state: 3
       sliding-window-size: 10
       sliding-window-type: count-based
       
       
            